{% set name = "astrophot" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astrophot-{{ version }}.tar.gz
  sha256: 13e50ae7c342ed3b2f30095d303334b3211cc4fbcdcb12c1d88289ef20135895

build:
  entry_points:
    - astrophot = astrophot:run_from_terminal
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-requirements-txt
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - astropy >=5.3
    - h5py >=3.8.0
    - matplotlib-base >=3.7
    - numpy >=1.24.0
    - pyro-ppl >=1.8.0
    - pyyaml >=6.0
    - requests >=2.30.0
    - scipy >=1.10.0
    - pytorch >=2.0.0
    - tqdm >=4.65.0

test:
  imports:
    - astrophot
  commands:
    - pip check
    - astrophot --help
  requires:
    - pip

about:
  home: https://github.com/Autostronomy/AstroPhot
  summary: A fast, flexible, automated, and differentiable astronomical image 2D forward modelling tool for precise parallel multi-wavelength photometry.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ConnorStoneAstro
